### PR TITLE
PLAYER-1089 shows control bar when accessibility its enabled

### PR DESCRIPTION
**Pull request by agarcia001**

### CODE REVIEW

**Comment by akshaydch11** [comment]
Is this PR ready to review ? 
You also need to add AccessibilityInfo for android as it alwaysOn controlbar behavior different on both platform.  We don't want that. Please make sure you test changed on android too.

**Comment by brol1dev** [comment]
@agarcia001 do we still need this PR?

**Comment by agarcia001** [comment]
Compare this solution with the Óscar ticket if not need this PR closet it

**Comment by brol1dev** [comment]
I'll close this ticket.

**Pull request closed without merging**
