### PR TITLE
[PLAYER-3933] Remove moreOptions button when ad is shown

### PR DESCRIPTION
**Pull request by cacel**
Remove moreOptions when Ad is shown

### CODE REVIEW

**Review by ipadilla4 — APPROVED** [review]
LGTM

**Review by brol1dev — COMMENTED** [review]
Does it apply to all ads? SSAI and CSAI?

**Comment by cacel** [comment]
@rcvrgs It applies for ads that use **AdPlaybackScreen** to show the ad.
Basically, I hide CC and MoreOptions buttons, by default the view is showing them.
This Screen was showing the same elements that videoContent Screen

**Review by brol1dev — COMMENTED** [review]
Do you use `AdPlaybackScreen` for SSAI?

**Comment by cacel** [comment]
@rcvrgs For SSAI, I post an **OOOoyalaPlayerAdStartedNotification**, that uses that Screen, using the AdSpot info to display metadata of the ad (title, clickurl, etc).

**Review by akshaydch11 — APPROVED** [review]
LGTM

**Comment by pilievOoyala** [comment]
LGTM

**Pull request merged**
