### PR TITLE
[PLAYER-4486] Fix player controls are cropped if player size is too small

### PR DESCRIPTION
**Pull request by alinag**
If player's size is too small and icons are cropped we should move them to more options using `"whenDoesNotFit":"moveToMoreOptions"`.

### CODE REVIEW

**Review by SergeyBicarte — APPROVED** [review]
LGTM

**Review by DmitriiMaslov — APPROVED** [review]
LGTM 
@isheftel-ooyala please have a look as well

**Review by isheftel-ooyala — APPROVED** [review]
LGTM

**Comment by DmitriiMaslov** [comment]
@alinag  Please resolve the conflicts.

**Pull request closed without merging**
