### PR TITLE
[PLAYER-3149] - [Apple TV] Closed captions are not shown when selected in TV settings.

### PR DESCRIPTION
**Pull request by ipadilla4**
Calling SDK method to avoid CC duplicates when using Skin SDK.

https://jira.corp.ooyala.com/browse/PLAYER-3149

### CODE REVIEW

**Comment by brol1dev** [comment]
is there a case in which the CC from the HLS Playlist (m3u8) are shown using the SkinSDK? Or does the Skin only support CC from content tree?

**Comment by ipadilla4** [comment]
My understanding is that Skin only supports CC from content tree to avoid duplicates.

**Review by brol1dev — APPROVED** [review]
LGTM, read comments added in our internal repos.

**Comment by akshaydch11** [comment]
LGTM

**Pull request merged**
