### PR TITLE
pulled new changes for skin-config

### PR DESCRIPTION
**Pull request by akshaydch11**

### CODE REVIEW

**Review by brol1dev — APPROVED** [review]
LGTM

**Comment by pilievOoyala** [comment]
This update is undoing my change to make the play icon '>' instead of 'h' when the font hasn't been loaded.  Are you sure you updated to the latest?
My changes were in the skin.json and skin-scheme.json file.

**Comment by akshaydch11** [comment]
@pilievOoyala Current commit id is "7278ab9" and as per https://github.com/ooyala/skin-config/commits/master
Looks like your fix was merged after we pull changes last time.

**Comment by pilievOoyala** [comment]
Ok I suck at reading. It's doing exactly what it's supposed to, I just read it wrong.

**Pull request merged**
