### PR TITLE
[PBA-3931] fix Ooyala SkinSDK so player duration/playhead are passed …

### PR DESCRIPTION
**Pull request by lental**
…through the AdPodCompleteParams

Also changed the build.gradle to use project dir instead of user.dir

### CODE REVIEW

**Comment by lental** [comment]
TODO: do the iOS side on Monday

**Comment by lental** [comment]
bump, please review

**Comment by lental** [comment]
another bump

**Comment by brol1dev** [comment]
LGTM

**Comment by brol1dev** [comment]
wait, i think this should be merged into dev not stable, right?

**Comment by Matthew-C** [comment]
looks good to me too. Did we really want to merge to stable?

**Comment by lental** [comment]
nope! good catch! switching it and merging

**Pull request closed without merging**
