### PR TITLE
[PLAYER-5607] Merged candidate into dev

### PR DESCRIPTION
**Pull request by maxkupetskii**
**Do not merge** !!! Until https://github.com/loginov-rocks approve

### CODE REVIEW

**Review by oSulyma — APPROVED** [review]
LGTM

**Review by loginov-rocks — CHANGES_REQUESTED** [review]
Hang on a minute, there is wrong conflicts resolving in JS side.

**Review by SergeyBicarte — APPROVED** [review]

**Review by AlinaVoronkovaEpam — APPROVED** [review]
LGTM

**Review by loginov-rocks — APPROVED** [review]
JS side fixed

**Pull request merged**
